# Generated by Django 3.2.5 on 2021-07-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_rename_content_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
