# Generated by Django 3.2.5 on 2021-07-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('cellphone', models.CharField(max_length=45)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=45)),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
