# Generated by Django 3.2.5 on 2021-07-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=20)),
                ('phone_numbers', models.IntegerField()),
                ('privacy', models.TextField(max_length=200)),
            ],
        ),
    ]
