# Generated by Django 3.2.5 on 2021-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('phone', models.PositiveIntegerField()),
                ('birth', models.DateField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
