# Generated by Django 3.2.5 on 2021-07-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210722_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=45),
        ),
    ]
