# Generated by Django 3.2.5 on 2021-07-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('other_info', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
